[package]
name = "dog-fetcher"
edition = "2021"
version = "0.2.0"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.93"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2.5.3"
wasmcloud-component = "0.2.0"
